name: Android CI

env:
  SAMPLE_PATH: Ceiba

on:
  push:
    branches:
      - master
  pull_request:
    types: [ opened, synchronize, reopened ]

jobs:

  build:
      runs-on: ubuntu-latest

      steps:
        - uses: actions/checkout@v1

        # Set Current Date As Env Variable
        - name: Set current date as env variable
          run: echo "date_today=$(date +'%Y-%m-%d')" >> $GITHUB_ENV

        # Set Repository Name As Env Variable
        - name: Set repository name as env variable
          run: echo "repository_name=$(echo '${{ github.repository }}' | awk -F '/' '{print $2}')" >> $GITHUB_ENV

        - name: Set Up JDK 11
          uses: actions/setup-java@v1
          with:
            java-version: 11

        - name: Change wrapper permissions
          run: chmod +x ./gradlew

        - name: Run gradle tests
          run: ./gradlew testDebug --stacktrace

        - name: Run Jacoco covergae
          run: ./gradlew jacocoTestReport --stacktrace

        - uses: pooi/coverage-comment@1.0.0
          with:
            github-token: ${{ secrets.GITHUB_TOKEN }}
            xml-test-report-path: ${SOURCE_PATH}/build/jacoco/jacoco.xml
