name: Android CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  lint:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: gradle

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build Lint
        run: ./gradlew lintDebug

      - name: Upload Build Lint Report
        uses: actions/upload-artifact@v2
        with:
          name: report
          path: app/build/reports/lint-results-debug.html

  test:

    needs: [ lint ]

    runs-on: ubuntu-latest

    steps:
      - name: Run Unit Tests
        run:  ./gradlew test

      - name: Upload Unit Test Report
        uses: actions/upload-artifact@v2
        with:
          name: test-report
          path: app/build/reports/tests/testDebugUnitTest/

  code_analysis:
    needs: [ test ]
    runs-on: ubuntu-latest
    steps:
      - name: Upload Code Anaylysis To SonarCloud
      run: ./gradlew build sonarqube --info
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

  jacoco_report:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: Grant execute permission for gradlew
      run: chmod +x gradlew

        - name: Run Module Coverage
          run: ./gradlew prodNormalDebugCoverage debugCoverage

            - name: Jacoco Report to PR
              id: jacoco
              uses: madrapps/jacoco-report@v1.2
              with:
                paths: |
                  ${{ github.workspace }}/app/build/reports/jacoco/prodNormalDebugCoverage/prodNormalDebugCoverage.xml,
                  ${{ github.workspace }}/math/build/reports/jacoco/debugCoverage/debugCoverage.xml,
                  ${{ github.workspace }}/text/build/reports/jacoco/debugCoverage/debugCoverage.xml
                token: ${{ secrets.GITHUB_TOKEN }}
                min-coverage-overall: 40
                min-coverage-changed-files: 60
                title: Code Coverage
                debug-mode: false

            - name: Get the Coverage info
              run: |
                echo "Total coverage ${{ steps.jacoco.outputs.coverage-overall }}"
                echo "Changed Files coverage ${{ steps.jacoco.outputs.coverage-changed-files }}"